wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    t:
      1:
      - 1
      - 5
      4: 3.9.7
      5: 0.10.15
      8:
      - 1
      - 3
